"""empty message

Revision ID: 8c51589c5671
Revises: b1d1f7ae4d5a
Create Date: 2021-03-02 22:08:36.238502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c51589c5671'
down_revision = 'b1d1f7ae4d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['season', 'episode'], ['episodes.season', 'episodes.episode'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
