"""empty message

Revision ID: b1d1f7ae4d5a
Revises: 
Create Date: 2021-03-01 23:32:01.128433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d1f7ae4d5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('runtime_in_minutes', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(length=128), nullable=False),
    sa.Column('writers', sa.String(length=512), nullable=False),
    sa.Column('actors', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('plot', sa.Text(), nullable=False),
    sa.Column('imdb_rating', sa.Numeric(), nullable=False),
    sa.Column('imdb_votes', sa.BigInteger(), nullable=False),
    sa.Column('imdb_id', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('season', 'episode'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    # ### end Alembic commands ###
